"""
CLIP embedding zero-shot generator identification.
"""

from __future__ import annotations

from typing import Any, Dict, List, Tuple

from backend.analysis.ml_models import _load_rgb_image, get_clip_bundle

GENERATOR_PROMPTS: Dict[str, str] = {
    "stable_diffusion": "a digital artwork generated by Stable Diffusion AI",
    "midjourney": "an image created by Midjourney generative AI",
    "dall_e": "an image generated by OpenAI DALL-E",
    "flux": "an image generated by Black Forest Labs Flux AI model",
    "adobe_firefly": "an image created with Adobe Firefly generative AI",
    "ideogram": "an image generated by Ideogram AI text-to-image",
    "leonardo": "an image created by Leonardo AI art generator",
    "authentic": "a real photograph captured by a camera",
}

GENERATOR_LABELS: Dict[str, str] = {
    "stable_diffusion": "Stable Diffusion",
    "midjourney": "Midjourney",
    "dall_e": "DALL-E",
    "flux": "Flux",
    "adobe_firefly": "Adobe Firefly",
    "ideogram": "Ideogram",
    "leonardo": "Leonardo",
    "authentic": "Authentic Photograph",
}


def detect_clip(image_path: str) -> Dict[str, Any]:
    bundle = get_clip_bundle()
    if not bundle:
        return {
            "score": 0.0,
            "confidence": 0.3,
            "method": "unavailable",
            "generator": "unknown",
            "generator_scores": {},
            "explanation": "CLIP model unavailable.",
        }

    try:
        import torch
        from PIL import Image

        rgb = _load_rgb_image(image_path)
        pil = Image.fromarray(rgb)
        labels = list(GENERATOR_PROMPTS.values())
        keys = list(GENERATOR_PROMPTS.keys())

        inputs = bundle["processor"](text=labels, images=pil, return_tensors="pt", padding=True)
        inputs = {k: v.to(bundle["device"]) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = bundle["model"](**inputs)
            logits = outputs.logits_per_image[0]
            probs = torch.softmax(logits, dim=0).cpu().numpy()

        ranked: List[Tuple[str, float]] = sorted(
            zip(keys, probs.tolist()),
            key=lambda x: x[1],
            reverse=True,
        )
        top_key, top_prob = ranked[0]
        authentic_prob = dict(ranked).get("authentic", 0.0)
        synthetic_prob = 1.0 - authentic_prob
        score = min(1.0, max(0.0, synthetic_prob * 1.15))

        generator_scores = {
            GENERATOR_LABELS[k]: round(float(p), 4) for k, p in ranked if k != "authentic"
        }

        if top_key == "authentic":
            prediction = "Authentic / Not AI-Generated"
            expl = (
                f"CLIP embeddings most closely match authentic photography "
                f"({authentic_prob:.0%} confidence)."
            )
        else:
            prediction = GENERATOR_LABELS[top_key]
            expl = (
                f"CLIP semantic match suggests {GENERATOR_LABELS[top_key]} "
                f"({top_prob:.0%} relative confidence). "
                f"Synthetic probability: {synthetic_prob:.0%}."
            )

        return {
            "score": round(score, 4),
            "confidence": round(min(0.92, max(0.45, float(top_prob) + 0.2)), 4),
            "method": bundle["name"],
            "generator": top_key,
            "generator_label": prediction,
            "generator_scores": generator_scores,
            "authentic_probability": round(float(authentic_prob), 4),
            "explanation": expl,
        }
    except Exception as exc:
        return {
            "score": 0.0,
            "confidence": 0.3,
            "method": "clip_error",
            "generator": "unknown",
            "generator_scores": {},
            "explanation": f"CLIP analysis failed: {exc}",
        }
